version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres-docker-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER_NAME: com_user_management_docker
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: com_user_management_docker
    volumes:
      - E:\docker_volumes\postgres:/var/lib/postgresql/data
  user-management-app:
#    image: user-management
    container_name: user-management-container
    build: .
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
#    expose:
#      - 8080
    restart: always
    depends_on:
      - db
    environment:
#      spring.datasource.url: jdbc:postgresql://db:5435/com_user_management3?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
#      spring.datasource.username: com_user_management3
#      spring.datasource.password: 123456
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/com_user_management_docker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_LIQUIBASE_DROP-FIRST: false
  portal-frontend-app:
    build: ../portal-frontend
    container_name: portal-frontend-app-container
    ports:
      - "3000:3000"
    depends_on:
      - user-management-app
    stdin_open: true
    tty: true